# Form implementation generated from reading ui file 'AlertWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Alert(object):
    def setupUi(self, Alert):
        Alert.setObjectName("Alert")
        Alert.resize(246, 131)
        Alert.setStyleSheet("background-color: rgb(193, 255, 216);")
        self.centralwidget = QtWidgets.QWidget(parent=Alert)
        self.centralwidget.setObjectName("centralwidget")
        self.Notice = QtWidgets.QLabel(parent=self.centralwidget)
        self.Notice.setGeometry(QtCore.QRect(30, 40, 191, 51))
        self.Notice.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Notice.setText("")
        self.Notice.setObjectName("Notice")
        Alert.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Alert)
        self.statusbar.setObjectName("statusbar")
        Alert.setStatusBar(self.statusbar)

        self.retranslateUi(Alert)
        QtCore.QMetaObject.connectSlotsByName(Alert)

    def retranslateUi(self, Alert):
        _translate = QtCore.QCoreApplication.translate
        Alert.setWindowTitle(_translate("Alert", "AlertWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Alert = QtWidgets.QMainWindow()
    ui = Ui_Alert()
    ui.setupUi(Alert)
    Alert.show()
    sys.exit(app.exec())
