# Form implementation generated from reading ui file 'AlertWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Alert(QtWidgets.QMainWindow):
    def setupUi(self, text):
        self.setObjectName("Alert")
        self.resize(246, 131)
        self.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        # Create central widget instance
        self.centralWidget = QtWidgets.QWidget(self)
        self.centralWidget.setObjectName("centralwidget")
        
        # Instantiate QLabel
        self.Notice = QtWidgets.QLabel(self.centralWidget)
        self.Notice.setGeometry(QtCore.QRect(30, 40, 191, 51))
        self.Notice.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Notice.setText(text)
        self.Notice.setObjectName("Notice")

        self.setCentralWidget(self.centralWidget)
        
        # Create status bar instance
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Alert", "AlertWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = Ui_Alert()
    window.show()
    sys.exit(app.exec())

