# Form implementation generated from reading ui file 'connect_server.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Connect_server(object):
    def setupUi(self, Connect_server,color='client'):
        Connect_server.setObjectName("Connect_server")
        Connect_server.resize(412, 387)
        if color ==  'server':
                Connect_server.setStyleSheet("background-color: rgb(255, 255, 255);")
        else:
                Connect_server.setStyleSheet("background-color: rgb(193, 255, 216);")
        self.centralwidget = QtWidgets.QWidget(parent=Connect_server)
        self.centralwidget.setObjectName("centralwidget")
        self.connect_server_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect_server_btn.setGeometry(QtCore.QRect(150, 270, 75, 23))
        self.connect_server_btn.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.connect_server_btn.setObjectName("connect_server_btn")
        self.IP_server = QtWidgets.QLabel(parent=self.centralwidget)
        self.IP_server.setGeometry(QtCore.QRect(80, 160, 71, 21))
        self.IP_server.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.IP_server.setObjectName("IP_server")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"")
        self.label.setObjectName("label")
        self.Port_server = QtWidgets.QLabel(parent=self.centralwidget)
        self.Port_server.setGeometry(QtCore.QRect(80, 210, 71, 21))
        self.Port_server.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.Port_server.setObjectName("Port_server")
        self.username_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(160, 160, 201, 21))
        self.username_input.setMouseTracking(True)
        self.username_input.setStyleSheet("color: qlineargradient(spread:pad, x1:0.75, y1:0.3575, x2:0.153, y2:0.585, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(160, 210, 201, 21))
        self.password_input.setObjectName("password_input")
        Connect_server.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Connect_server)
        self.statusbar.setObjectName("statusbar")
        Connect_server.setStatusBar(self.statusbar)

        self.retranslateUi(Connect_server)
        QtCore.QMetaObject.connectSlotsByName(Connect_server)

    def retranslateUi(self, Connect_server):
        _translate = QtCore.QCoreApplication.translate
        Connect_server.setWindowTitle(_translate("Connect_server", "connect_server_window"))
        self.connect_server_btn.setText(_translate("Connect_server", "Connect"))
        self.IP_server.setText(_translate("Connect_server", "IP"))
        self.label.setText(_translate("Connect_server", "Server"))
        self.Port_server.setText(_translate("Connect_server", "Port"))
        self.username_input.setText(_translate("Connect_server", "Enter IP of server"))
        self.password_input.setText(_translate("Connect_server", "Enter Port of server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Connect_server = QtWidgets.QMainWindow()
    ui = Ui_Connect_server()
    ui.setupUi(Connect_server)
    Connect_server.show()
    sys.exit(app.exec())
