# Form implementation generated from reading ui file 'feature_server.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Feature_sever(object):
    def setupUi(self, Feature_sever):
        Feature_sever.setObjectName("Feature_sever")
        Feature_sever.resize(414, 390)
        Feature_sever.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=Feature_sever)
        self.centralwidget.setObjectName("centralwidget")
        self.Showfile_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Showfile_btn.setGeometry(QtCore.QRect(50, 70, 75, 23))
        self.Showfile_btn.setObjectName("Showfile_btn")
        self.show_user_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.show_user_btn.setGeometry(QtCore.QRect(50, 130, 75, 23))
        self.show_user_btn.setObjectName("show_user_btn")
        self.Stop_server = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Stop_server.setGeometry(QtCore.QRect(230, 250, 75, 23))
        self.Stop_server.setObjectName("Stop_server")
        self.Start_server = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Start_server.setGeometry(QtCore.QRect(100, 250, 75, 23))
        self.Start_server.setObjectName("Start_server")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 70, 181, 20))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 130, 181, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        Feature_sever.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Feature_sever)
        self.statusbar.setObjectName("statusbar")
        Feature_sever.setStatusBar(self.statusbar)

        self.retranslateUi(Feature_sever)
        QtCore.QMetaObject.connectSlotsByName(Feature_sever)

    def retranslateUi(self, Feature_sever):
        _translate = QtCore.QCoreApplication.translate
        Feature_sever.setWindowTitle(_translate("Feature_sever", "Feature_server_window"))
        self.Showfile_btn.setText(_translate("Feature_sever", "Show file"))
        self.show_user_btn.setText(_translate("Feature_sever", "Show user"))
        self.Stop_server.setText(_translate("Feature_sever", "Stop server"))
        self.Start_server.setText(_translate("Feature_sever", "Start server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Feature_sever = QtWidgets.QMainWindow()
    ui = Ui_Feature_sever()
    ui.setupUi(Feature_sever)
    Feature_sever.show()
    sys.exit(app.exec())
