# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_P2P_APP(object):
    def setupUi(self, P2P_APP):
        P2P_APP.setObjectName("P2P_APP")
        P2P_APP.resize(414, 392)
        P2P_APP.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        P2P_APP.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(parent=P2P_APP)
        self.centralwidget.setObjectName("centralwidget")
        self.header = QtWidgets.QLabel(parent=self.centralwidget)
        self.header.setGeometry(QtCore.QRect(20, 40, 381, 51))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(24)
        self.header.setFont(font)
        self.header.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.header.setObjectName("header")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(180, 90, 51, 51))
        self.widget.setStyleSheet("border-image: url(:/pic/share.png);")
        self.widget.setObjectName("widget")
        self.sharefile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sharefile.setGeometry(QtCore.QRect(70, 200, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sharefile.setFont(font)
        self.sharefile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sharefile.setObjectName("sharefile")
        self.download = QtWidgets.QPushButton(parent=self.centralwidget)
        self.download.setGeometry(QtCore.QRect(260, 200, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.download.setFont(font)
        self.download.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.download.setObjectName("download")
        self.want = QtWidgets.QLabel(parent=self.centralwidget)
        self.want.setGeometry(QtCore.QRect(170, 140, 71, 20))
        self.want.setObjectName("want")
        self.disconect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.disconect.setGeometry(QtCore.QRect(160, 340, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.disconect.setFont(font)
        self.disconect.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.disconect.setObjectName("disconect")
        P2P_APP.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=P2P_APP)
        self.statusbar.setObjectName("statusbar")
        P2P_APP.setStatusBar(self.statusbar)

        self.retranslateUi(P2P_APP)
        QtCore.QMetaObject.connectSlotsByName(P2P_APP)
        
        #connect function and button
        

    def retranslateUi(self, P2P_APP):
        _translate = QtCore.QCoreApplication.translate
        P2P_APP.setWindowTitle(_translate("P2P_APP", "P2P APP"))
        self.header.setText(_translate("P2P_APP", "SHARE FILE APPLICATION"))
        self.sharefile.setText(_translate("P2P_APP", "SHARE FILE"))
        self.download.setText(_translate("P2P_APP", "DOWNLOAD"))
        self.want.setText(_translate("P2P_APP", "You want to: "))
        self.disconect.setText(_translate("P2P_APP", "DISCONECT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    P2P_APP = QtWidgets.QMainWindow()
    ui = Ui_P2P_APP()
    ui.setupUi(P2P_APP)
    P2P_APP.show()
    sys.exit(app.exec())
