# Form implementation generated from reading ui file 'pagedown.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Download(object):
    def setupUi(self, Download):
        Download.setObjectName("Download")
        Download.resize(407, 391)
        Download.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(parent=Download)
        self.centralwidget.setObjectName("centralwidget")
        self.header_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.header_2.setGeometry(QtCore.QRect(20, 30, 381, 51))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(24)
        self.header_2.setFont(font)
        self.header_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.header_2.setObjectName("header_2")
        self.back2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back2.setGeometry(QtCore.QRect(0, 0, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.back2.setFont(font)
        self.back2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back2.setObjectName("back2")
        self.search_box = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_box.setGeometry(QtCore.QRect(110, 160, 251, 20))
        self.search_box.setObjectName("search_box")
        self.search_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(20, 160, 75, 23))
        self.search_btn.setObjectName("search_btn")
        self.IP_text_box = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.IP_text_box.setGeometry(QtCore.QRect(20, 260, 151, 20))
        self.IP_text_box.setObjectName("IP_text_box")
        self.Port_text_box = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Port_text_box.setGeometry(QtCore.QRect(180, 260, 61, 20))
        self.Port_text_box.setObjectName("Port_text_box")
        self.filename_text_box = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.filename_text_box.setGeometry(QtCore.QRect(250, 260, 141, 20))
        self.filename_text_box.setObjectName("filename_text_box")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 240, 21, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 240, 51, 20))
        self.label_5.setObjectName("label_5")
        self.fetch_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fetch_btn.setGeometry(QtCore.QRect(170, 290, 75, 23))
        self.fetch_btn.setObjectName("fetch_btn")
        Download.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Download)
        self.statusbar.setObjectName("statusbar")
        Download.setStatusBar(self.statusbar)

        self.retranslateUi(Download)
        QtCore.QMetaObject.connectSlotsByName(Download)

    def retranslateUi(self, Download):
        _translate = QtCore.QCoreApplication.translate
        Download.setWindowTitle(_translate("Download", "MainWindow"))
        self.header_2.setText(_translate("Download", "SHARE FILE APPLICATION"))
        self.back2.setText(_translate("Download", "BACK"))
        self.search_btn.setText(_translate("Download", "Search"))
        self.label_3.setText(_translate("Download", "IP"))
        self.label_4.setText(_translate("Download", "Port"))
        self.label_5.setText(_translate("Download", "File name"))
        self.fetch_btn.setText(_translate("Download", "Fetch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Download = QtWidgets.QMainWindow()
    ui = Ui_Download()
    ui.setupUi(Download)
    Download.show()
    sys.exit(app.exec())
